print "Hi!"
print "Welcome to XPack - A simple package manager for arch linux made in python."
print "HELP TIP: Pressed something you din't want to? Its ok, just press Ctrl+c there or click the correct thing or click  on 'Close All'"

print "REMEMBER: XPACK DEPENDS ON PACKER"

print "\nHow does XPack work?"
print "--------------------\n"
print "How does it UPGRADE?"
print "Easy enough... it just runs 'sudo pacman -Syu'\n"
print "How does it SEARCH?"
print "It runs 'packer -Ss (searched keywork)'\n"
print "How does it INSTALL?"
print "It runs 'packer -S (package/s)'"
print " + AUR supported!\n"
print "How does it REMOVE?"
print "It runs 'sudo pacman -Rs (package/s)'\n"
print "You may ask why it gives-\n - pacman: no process found\n - packer: no process found\nWell, its just that every time a section is clicked and session is started, it makes sure no other pacman or packer is running for security reasons."
print "\nMORE AT:http://vibhaas.github.io/XPack"
